import { leaves } from "../schema-walk";
import { Schema, SchemaEntry } from "../types";

const NUMERIC_FORMATS = new Set(["port", "int", "nat", "duration"]);

function tsType(entry: SchemaEntry): string {
  if (entry.tsType) return entry.tsType;

  let base: string;
  if (Array.isArray(entry.format)) base = entry.format.map((value) => JSON.stringify(value)).join(" | ");
  else if (entry.format === "strict-boolean" || typeof entry.default === "boolean") base = "boolean";
  else if (NUMERIC_FORMATS.has(String(entry.format)) || typeof entry.default === "number") base = "number";
  else base = "string";

  return entry.nullable || entry.default === null ? `${base} | null` : base;
}

/**
 * Renders a schema as a TypeScript module exporting a flat map of dotted key to value type.
 *
 * A flat interface rather than recursive conditional types is what keeps the consumer side to a
 * single generic parameter: `get<P extends keyof K & string>(key: P): K[P]`.
 */
export function emitTypes(schema: Schema, options: { interfaceName?: string } = {}): string {
  const name = options.interfaceName ?? "ConfigKeys";
  const entries = leaves(schema);

  const banner =
    "// Generated by `revopush-config types`. Do not edit.\n" +
    "// Re-run the generator after changing schema.json.\n\n";

  if (entries.length === 0) return `${banner}export interface ${name} {}\n`;

  const body = entries
    .map(({ path, entry }) => {
      const doc = entry.doc ? `  /** ${entry.doc} */\n` : "";
      return `${doc}  ${JSON.stringify(path)}: ${tsType(entry)};`;
    })
    .join("\n");

  return `${banner}export interface ${name} {\n${body}\n}\n`;
}
