// Generated by `revopush-config types`. Do not edit.
// Re-run the generator after changing schema.json.

import type { ReadonlyConfig } from "../../../src/index";

export interface ConfigKeys {
  /** Redis host */
  "redis.host": string;
  /** Redis port */
  "redis.port": number;
  /** R2 S3-compatible endpoint */
  "platform.saas.cloudflare.uri": string;
  /** Daily counters table */
  "platform.azure.tables.daily": string;
}

export interface Settings {
  readonly redis: RedisSettings;
  readonly platform: PlatformSettings;
}

/** redis */
export interface RedisSettings {
  /** Redis host */
  readonly host: string;
  /** Redis port */
  readonly port: number;
}

/** platform */
export interface PlatformSettings {
  readonly saas: PlatformSaasSettings;
  readonly azure: PlatformAzureSettings;
}

/** platform.saas */
export interface PlatformSaasSettings {
  readonly cloudflare: PlatformSaasCloudflareSettings;
}

/** platform.saas.cloudflare */
export interface PlatformSaasCloudflareSettings {
  /** R2 S3-compatible endpoint */
  readonly uri: string;
}

/** platform.azure */
export interface PlatformAzureSettings {
  readonly tables: PlatformAzureTablesSettings;
}

/** platform.azure.tables */
export interface PlatformAzureTablesSettings {
  /** Daily counters table */
  readonly daily: string;
}

/** Binds the accessors to a config. A factory, so this file imports no module of yours. */
export const bind = (c: ReadonlyConfig<ConfigKeys>): Settings => ({
  redis: {
    get host() {
      return c.get("redis.host");
    },
    get port() {
      return c.get("redis.port");
    },
  },
  platform: {
    saas: {
      cloudflare: {
        get uri() {
          return c.get("platform.saas.cloudflare.uri");
        },
      },
    },
    azure: {
      tables: {
        get daily() {
          return c.get("platform.azure.tables.daily");
        },
      },
    },
  },
});
